name: ci

on: [push]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install and run linters
      run: | 
        pip install pipenv
        pipenv install --dev
        pipenv run pylint ing_ynab
        pipenv run black --check ing_ynab
  check:
    name: Check setup.py requirements
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Verify dependencies
      run: | 
        pip install pipenv
        pipenv install --dev
        pipenv run pipenv-setup --check
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install and run pytest
      run: | 
        pip install pipenv
        pipenv install --dev
        pipenv run python -m pytest
