name: tags

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Login
      run: docker login docker.pkg.github.com -u bahlo -p "${{ secrets.GITHUB_TOKEN }}"
    - name: Build and publish
      run: |
        echo "${{ github.ref }}"
        export TAG=$(echo "${{ github.ref }}" | sed 's/^refs\/tags\/v//g')
        docker build -t docker.pkg.github.com/bahlo/ing_ynab/ing_ynab:$TAG
        docker push docker.pkg.github.com/bahlo/ing_ynab/ing_ynab:$TAG