name: tags

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Login
      run: docker login docker.pkg.github.com -u bahlo -p "${{ secrets.GITHUB_TOKEN }}"
    - name: Build
      run: docker build -t docker.pkg.github.com/bahlo/ing_ynab/ing_ynab:${{ github.ref }} .
    - name: Publish
      run: docker push docker.pkg.github.com/bahlo/ing_ynab/ing_ynab:${{ github.ref }}